

use ExtUtils::MakeMaker;
# See lib/ExtUtils/MakeMaker.pm for details of how to influence
# the contents of the Makefile that is written.
WriteMakefile(
    NAME         => 'Jenkins',
    VERSION_FROM => 'lib/Jenkins.pm', # finds \$VERSION
    AUTHOR       => 'Jiqing Yao (jiqingyao@gmail.com)',
    ABSTRACT     => 'Module abstract (<= 44 characters) goes here',
    PREREQ_PM    => {
                     'Test::Simple' => 0.44,
                    },
);
